version: '3.5'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8050:80'
  rabbit:
    hostname: rabbit
    build:
      dockerfile: Dockerfile
      context: ./rabbit
  api:
    hostname: api
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server/src:/app/src
    env_file:
      - .env
    depends_on:
      - rabbit
  bot:
    hostname: bot
    build:
      dockerfile: Dockerfile
      context: ./bot
    volumes:
      - ./bot/src:/app/src
    env_file:
      - .env
    depends_on:
      - rabbit
  client:
    hostname: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
